/**
 * Per-company research memo ("IC memo") PDF: drawing + generation pipeline.
 *
 * Renders the STORED deep-dive analysis (`company_analysis`) into a branded
 * A4 memo — this module makes NO LLM calls; every narrative comes verbatim
 * from the stored row with its basis/confidence tag, and every scenario $
 * figure was computed by `buildCompsTable` inside the pure render model.
 * `generateCompanyReport` loads (with an explicit ownership check, since it
 * runs under the service-role client), builds, and uploads to the private
 * `reports` bucket at {userId}/{date}-{slug}-memo.pdf.
 */
import "server-only";
import { PDFDocument, StandardFonts } from "pdf-lib";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { CompanyWithRelations, Database } from "@/lib/types";
import {
  AMBER,
  GREEN,
  HAIRLINE,
  INK,
  MUTED,
  PdfCursor,
  RED,
  TEAL,
  drawLogo,
  type PdfColor,
} from "@/lib/reports/pdf-kit";
import {
  buildCompanyReportModel,
  type CompanyReportModel,
  type IcBadge,
  type ReportSection,
  type TaggedText,
} from "@/lib/reports/company-report-model";
import { isStale } from "@/lib/analysis/staleness";
import { formatDate } from "@/lib/utils";

type DB = SupabaseClient<Database>;

const REPORT_BUCKET = "reports";

const BADGE_COLORS: Record<IcBadge["color"], PdfColor> = {
  green: GREEN,
  muted: MUTED,
  red: RED,
};

/** Draw a labelled paragraph ("Label — text [tag]"), skipping null fields. */
function labelled(c: PdfCursor, label: string | null, t: TaggedText | null) {
  if (!t) return;
  if (label) {
    c.ensureSpace(28);
    c.text(label, { size: 8, bold: true, color: MUTED });
  }
  c.paragraph(t.text, { tag: t.tag ?? undefined });
  c.gap(4);
}

/** Draw the IC rating badge inline at the cursor. */
function drawBadge(c: PdfCursor, badge: IcBadge) {
  const size = 9;
  const w = badge.label.length * size * 0.62 + 14;
  c.ensureSpace(22);
  c.y -= 14;
  const color = BADGE_COLORS[badge.color];
  c.page.drawRectangle({
    x: c.margin,
    y: c.y - 4,
    width: w,
    height: 16,
    borderColor: color,
    borderWidth: 0.75,
  });
  c.page.drawText(badge.label.toUpperCase(), {
    x: c.margin + 7,
    y: c.y,
    size,
    font: c.boldFont,
    color,
  });
  c.y -= 10;
}

/** Render the whole memo from the pure model. Drawing only — no data access. */
export async function buildCompanyReportPdf(
  model: CompanyReportModel,
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const c = new PdfCursor(doc, font, bold, {
    companyName: model.companyName,
    top: 800,
  });
  const M = c.margin;

  // --- Page-1 branded header (same geometry as the digest: logo box 30). ---
  let y = 800;
  drawLogo(c.page, M, y + 28, 30);
  c.page.drawText("Automation Investment", { x: M + 42, y: y + 16, size: 13, font: bold, color: INK });
  c.page.drawText("Intelligence Platform", { x: M + 42, y: y + 3, size: 10, font, color: MUTED });
  const rLabel = "RESEARCH MEMO";
  c.page.drawText(rLabel, {
    x: c.right - bold.widthOfTextAtSize(rLabel, 9),
    y: y + 16,
    size: 9,
    font: bold,
    color: TEAL,
  });
  const gen = `Generated ${formatDate(model.generatedAt)}`;
  c.page.drawText(gen, {
    x: c.right - font.widthOfTextAtSize(gen, 9),
    y: y + 3,
    size: 9,
    font,
    color: MUTED,
  });
  y -= 34;
  c.page.drawLine({ start: { x: M, y }, end: { x: c.right, y }, thickness: 1.25, color: TEAL });
  y -= 26;
  c.page.drawText(model.companyName, { x: M, y, size: 18, font: bold, color: INK });
  y -= 16;
  c.y = y;

  // Stale notice: honest amber caution when underlying data moved on.
  if (model.stale) {
    c.text(
      "Note: underlying data changed after this analysis was generated — re-run the deep dive for fresh figures.",
      { size: 8.5, color: AMBER },
    );
    c.gap(2);
  }

  // Snapshot strip.
  c.ensureSpace(44);
  let sx = M;
  const colW = c.contentWidth / model.snapshot.length;
  for (const stat of model.snapshot) {
    c.page.drawText(stat.label, { x: sx, y: c.y - 8, size: 7.5, font, color: MUTED });
    c.page.drawText(stat.value, { x: sx, y: c.y - 22, size: 10.5, font: bold, color: INK });
    sx += colW;
  }
  c.y -= 34;
  c.rule();

  for (const section of model.sections) drawSection(c, section);

  // Footer on the last page.
  c.page.drawText(
    "Generated by Automation Investment Intelligence Platform · narratives carry basis/confidence tags; comps are illustrative, not a forecast.",
    { x: M, y: 32, size: 7, font, color: MUTED },
  );

  return doc.save();
}

function drawSection(c: PdfCursor, s: ReportSection): void {
  switch (s.id) {
    case "executive_summary": {
      c.sectionTitle(s.title);
      if (s.badge) drawBadge(c, s.badge);
      labelled(c, "Thesis", s.thesis);
      labelled(c, "Value proposition", s.valueProp);
      if (s.strengths.length) {
        c.ensureSpace(24);
        c.text("Strengths", { size: 8, bold: true, color: MUTED });
        for (const t of s.strengths) c.bullet(`${t.text}${t.tag ? `  ${t.tag}` : ""}`);
        c.gap(4);
      }
      if (s.weaknesses.length) {
        c.ensureSpace(24);
        c.text("Weaknesses", { size: 8, bold: true, color: MUTED });
        for (const t of s.weaknesses) c.bullet(`${t.text}${t.tag ? `  ${t.tag}` : ""}`);
        c.gap(4);
      }
      labelled(c, "Positioning", s.positioning);
      labelled(c, "Most likely outcome", s.mostLikelyOutcome);
      break;
    }
    case "business_moat": {
      c.sectionTitle(s.title);
      if (s.technology) {
        const suffix = s.moatRating != null ? ` (moat rating ${s.moatRating}/10)` : "";
        labelled(c, `Core technology${suffix}`, s.technology);
      }
      labelled(c, "Business model", s.businessModel);
      labelled(c, "Unit economics", s.unitEconomics);
      for (const row of s.financials) labelled(c, row.label, row.field);
      for (const row of s.market) labelled(c, row.label, row.field);
      if (s.moatBars.length) {
        c.ensureSpace(20 + s.moatBars.length * 18);
        c.text("Strategic moat", { size: 8, bold: true, color: MUTED });
        const barX = c.margin + 130;
        const barW = c.contentWidth - 130 - 40;
        for (const bar of s.moatBars) {
          c.ensureSpace(18);
          c.y -= 12;
          c.page.drawText(bar.label, { x: c.margin, y: c.y, size: 8.5, font: c.font, color: INK });
          c.page.drawRectangle({ x: barX, y: c.y - 1, width: barW, height: 7, color: HAIRLINE });
          c.page.drawRectangle({ x: barX, y: c.y - 1, width: barW * bar.fraction, height: 7, color: TEAL });
          c.page.drawText(`${bar.score}/10`, { x: barX + barW + 8, y: c.y, size: 8.5, font: c.font, color: MUTED });
          c.y -= 6;
        }
        c.gap(6);
      }
      labelled(c, null, s.moatNarrative);
      break;
    }
    case "competitive_landscape": {
      c.sectionTitle(s.title);
      labelled(c, null, s.narrative);
      if (s.tiers.length) {
        c.ensureSpace(24);
        c.text("Threat tiers", { size: 8, bold: true, color: MUTED });
        for (const t of s.tiers) c.bullet(`${t.name} — ${t.tier}`);
        c.gap(4);
      }
      if (s.matrix && s.matrix.threats.length) {
        const cols = [0, 170, 250, 330, 410];
        const headers = ["Capability matrix (1–10)", "IP depth", "GTM", "Capital eff.", "Retention"];
        c.ensureSpace(30 + (s.matrix.threats.length + 1) * 16);
        c.y -= 10;
        headers.forEach((h, i) =>
          c.page.drawText(h, { x: c.margin + cols[i], y: c.y, size: 8, font: c.font, color: MUTED }),
        );
        c.y -= 14;
        c.page.drawText(`${s.matrix.target} (target) vs. top threats`, {
          x: c.margin,
          y: c.y,
          size: 8,
          font: c.font,
          color: MUTED,
        });
        c.y -= 15;
        for (const r of s.matrix.threats) {
          const cells = [
            r.name,
            r.ip_depth?.toString() ?? "—",
            r.gtm_velocity?.toString() ?? "—",
            r.capital_efficiency?.toString() ?? "—",
            r.workflow_retention?.toString() ?? "—",
          ];
          cells.forEach((cell, i) =>
            c.page.drawText(cell, { x: c.margin + cols[i], y: c.y, size: 9, font: c.font, color: INK }),
          );
          c.y -= 15;
        }
        c.gap(6);
      }
      break;
    }
    case "valuation_comps": {
      c.sectionTitle(s.title);
      const p = s.provenance;
      c.paragraph(
        `Base revenue ${p.baseRevenue}${p.baseRevenueSource ? ` (${p.baseRevenueSource})` : ""} · peer multiples p25 ${p.multiples.p25} / median ${p.multiples.median} / p75 ${p.multiples.p75} · ${p.nPeers} peers · ${p.nSecVerified} SEC-verified`,
        { size: 8.5, color: MUTED },
      );
      c.gap(4);
      const cols = [0, 130, 250, 370];
      const headers = ["Year", "Bear (p25)", "Base (median)", "Bull (p75)"];
      c.ensureSpace(30 + (s.cells.length + 1) * 16);
      headers.forEach((h, i) =>
        c.page.drawText(h, { x: c.margin + cols[i], y: c.y - 8, size: 8, font: c.font, color: MUTED }),
      );
      c.y -= 22;
      for (const row of s.cells) {
        const cells = [String(row.year), row.bear, row.base, row.bull];
        cells.forEach((cell, i) =>
          c.page.drawText(cell, { x: c.margin + cols[i], y: c.y, size: 9.5, font: c.font, color: INK }),
        );
        c.y -= 15;
      }
      c.gap(4);
      c.paragraph(s.disclaimer, { size: 8, color: MUTED });
      c.gap(4);
      break;
    }
    case "historical_analogue":
    case "outlook_exit": {
      c.sectionTitle(s.title);
      labelled(c, null, s.body);
      break;
    }
    case "ic_conclusion": {
      c.sectionTitle(s.title);
      if (s.badge) drawBadge(c, s.badge);
      labelled(c, "Bull case", s.bull);
      labelled(c, "Bear case", s.bear);
      labelled(c, "Recommendation", s.recommendation);
      break;
    }
  }
}

export interface CompanyReportResult {
  path?: string;
  stale?: boolean;
  error?: string;
}

/**
 * Load → verify ownership → build model → draw PDF → upload. Runs under the
 * service-role client (bypasses RLS), so the `company.user_id === userId`
 * check is the authorization boundary (T-x47-01). Returns a typed result —
 * never throws to the caller.
 */
export async function generateCompanyReport(
  supabase: DB,
  { userId, companyId }: { userId: string; companyId: string },
): Promise<CompanyReportResult> {
  try {
    const { data: company, error: coErr } = await supabase
      .from("companies")
      .select("*, investments(*), valuations(*), funding_rounds(*), news(*)")
      .eq("id", companyId)
      .maybeSingle();
    if (coErr) return { error: coErr.message };
    const co = company as unknown as (CompanyWithRelations & { user_id: string }) | null;
    if (!co || co.user_id !== userId) return { error: "Company not found." };

    const { data: analysis, error: anErr } = await supabase
      .from("company_analysis")
      .select("*")
      .eq("company_id", companyId)
      .maybeSingle();
    if (anErr) return { error: anErr.message };
    if (!analysis) return { error: "No analysis yet — run a deep dive first." };

    const { data: competitors } = await supabase
      .from("competitors")
      .select("*")
      .eq("company_id", companyId);

    // Staleness mirrors the company page: latest valuation/competitor change
    // strictly after generated_at (isStale errs toward not-stale).
    const latestDataChange = [
      ...co.valuations.map((v) => v.created_at),
      ...(competitors ?? []).map((cp) => cp.updated_at ?? cp.created_at),
    ]
      .filter((d): d is string => Boolean(d))
      .sort()
      .at(-1);
    const stale = isStale(analysis.generated_at, latestDataChange);

    const date = new Date().toISOString().slice(0, 10);
    const model = buildCompanyReportModel(co, analysis, competitors ?? [], {
      generatedAt: date,
      stale,
    });
    const pdf = await buildCompanyReportPdf(model);

    const path = `${userId}/${date}-${model.slug}-memo.pdf`;
    const { error: upErr } = await supabase.storage
      .from(REPORT_BUCKET)
      .upload(path, pdf, { contentType: "application/pdf", upsert: true });
    if (upErr) return { error: upErr.message };

    return { path, stale };
  } catch (e) {
    return { error: (e as Error).message };
  }
}
